### PR TITLE
Remove scroll bar from footer

### PR DESCRIPTION
**Pull request by Eyas**

### CODE REVIEW

**Comment by durka** [comment]
This seems to break the [text autosizing hack](https://github.com/DevProgress/my-vote-matters/blob/master/js/main.js#L152-L165), which should prevent a scrollbar from ever actually appearing -- did you see one? There is probably a better way to do it than that loop, anyway, but that's what I saw recommended on SO.

**Comment by Eyas** [comment]
Yeah I actually see scrollbars consistently on Chrome and Edge on Windows.

**Comment by durka** [comment]
Bah. OK we need to find another way to size that text to the footer then.

**Comment by Eyas** [comment]
How are you trying to size the footer text? Trying to understand the point of the hack.

**Comment by durka** [comment]
I just want the text to mostly fill the footer without going onto two lines.

**Comment by Eyas** [comment]
May I suggest using [`vh`, or `vmin` instead here?](https://web-design-weekly.com/2014/11/18/viewport-units-vw-vh-vmin-vmax/). This should work great for the footer.

For the header, per issue #32, viewport-relative sizing might provide a close approximation, but we might want to keep that logic there.

**Comment by durka** [comment]
Yes, that should do it. I had read somewhere that they don't work on Android but caniuse.com seems to say it's fine.

**Comment by durka** [comment]
Superseded by recent commits. Thanks for the vh tip!

**Pull request closed without merging**
