### PR TITLE
draw polaroid frame w/ JS

### LINKED ISSUE #4: draw polaroid frame according to camera aspect ratio
The polaroid frame is a fixed image, but different cameras have different sizes (esp. phone cameras, which change size when you rotate the phone). Use a canvas to get rid of the fixed image and adapt to whatever the camera size happens to be.

### PR DESCRIPTION
**Pull request by durka**
Fixes #4.

### CODE REVIEW

**Comment by durka** [comment]
Screenshot:

**Comment by durka** [comment]
Rebased on the new design.

New screenshot:

**Comment by durka** [comment]
Mobile screenshot:



It still doesn't work so great in landscape mode. The popup is too tall and scrolling doesn't work (it scrolls the page behind the popup). But we can fix that later, probably by reformatting (or eliminating!) the popup.

**Review by dglazkov — APPROVED** [review]
LGTM.

**Comment by durka** [comment]
testing 1 2 3

**Comment by durka** [comment]
... 4 5 6

**Pull request merged**
