### PR TITLE
Landing page layout

### PR DESCRIPTION
**Pull request by durka**

### CODE REVIEW

**Comment by durka** [comment]
Desktop screenshot:

desktop

Phone:

phone

**Comment by dglazkov** [comment]
Ready to land this? :)

**Comment by durka** [comment]
Yeah sure. I noticed that the share button images need to be made transparent, but that's minor.

Another thing is that I made the canvas automatically adjust to the size of the device screen. That means photos posted from different browsers will be different sizes. This could be fixed, if we care, by drawing to an invisible fixed-size canvas. Thoughts?

**Review by dglazkov — APPROVED** [review]
LGTM.

**Comment by dglazkov** [comment]
re: different sizes, let's file a bug?

**Pull request merged**
